name: ta
channels:
  - conda-forge
  - defaults
channel_priority: strict
dependencies:
  - python=3.10
  - gdal
  - richdem
  - streamlit
  - geopandas
  - ezdxf
  - numpy
  - pandas
  - matplotlib
  - scipy
  - rasterio
  - sqlalchemy
  - psycopg2
  - pyvista
  - requests
  - pip
  - pip:
    - stpyvista
