name: ta
channels:
  - conda-forge
node_properties:
  - channel_priority=strict
dependencies:
  - python=3.10
  - gdal=3.10.3
  - richdem=2.3.0
  - streamlit>=1.30.0
  - geopandas=0.14.3
  - ezdxf=1.4.2
  - numpy=1.26.4
  - pandas=2.2.2
  - matplotlib=3.8.4
  - scipy=1.13.1
  - rasterio=1.3.10
  - sqlalchemy=2.0.31
  - psycopg2=2.9.9
  - pyvista=0.43.7
  - requests=2.32.3
  - pip
  - pip:
    - stpyvista==0.1.4
