name: ta
channels:
    - conda-forge
    - defaults
channel_priority: strict
dependencies:
    - python=3.10
    - gdal=3.11.4
    - richdem=2.3.0
    - streamlit>=1.49.0
    - geopandas=1.1.1
    - ezdxf=1.4.2
    - numpy=2.3.3
    - pandas=2.3.2
    - matplotlib=3.10.6
    - scipy=1.16.2
    - rasterio=1.4.3
    - sqlalchemy=2.0.43
    - psycopg2=2.9.10
    - pyvista=0.46.3
    - requests=2.32.5
    - pip
    - pip:
          - stpyvista==0.1.4
